dist: bionic

services:
  - docker

script:
  - docker login -u zhangdber -p 123456aaa docker.io
  - docker build -t zhangdber/eck-operator:1.2.1-arm-tmp  -f Dockerfile-tmp .
  - docker push zhangdber/eck-operator:1.2.1-arm-tmp
    
    
arch:
  - arm64
