{{- $operatorNSIsManaged := has .Values.operator.namespace .Values.config.managedNamespaces -}}
{{- if not $operatorNSIsManaged -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.operator.name }}
  namespace: {{ .Values.operator.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.operator.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.operator.name }}
  namespace: {{ .Values.operator.namespace }}
{{- end -}}
